"""rename item to trade and add offer

Revision ID: bedfcb3b354d
Revises: 993ec8b86843
Create Date: 2022-01-08 23:37:08.060893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic
revision = 'bedfcb3b354d'
down_revision = '993ec8b86843'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trade',
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('what_do', sa.Text(), server_default='trade', nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('size', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id', 'user_id', 'product_id')
    )
    op.create_index(op.f('ix_trade_id'), 'trade', ['id'], unique=True)
    op.create_table('offer',
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('trade_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Text(), server_default='pending', nullable=False),
    sa.ForeignKeyConstraint(['trade_id'], ['trade.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'trade_id')
    )
    op.create_index(op.f('ix_offer_status'), 'offer', ['status'], unique=False)
    op.drop_column('product', 'what_do')
    op.drop_column('product', 'price')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('product', sa.Column('what_do', sa.TEXT(), server_default=sa.text("'trade'::text"), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_offer_status'), table_name='offer')
    op.drop_table('offer')
    op.drop_index(op.f('ix_trade_id'), table_name='trade')
    op.drop_table('trade')
    # ### end Alembic commands ###

