"""add item table

Revision ID: db5b72b7a215
Revises: 993ec8b86843
Create Date: 2021-12-13 20:28:55.379950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic
revision = 'db5b72b7a215'
down_revision = '993ec8b86843'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item',
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('what_do', sa.Text(), server_default='trade', nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('size', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id', 'user_id', 'product_id')
    )
    op.create_index(op.f('ix_item_id'), 'item', ['id'], unique=True)
    op.drop_column('product', 'what_do')
    op.drop_column('product', 'price')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('product', sa.Column('what_do', sa.TEXT(), server_default=sa.text("'trade'::text"), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_item_id'), table_name='item')
    op.drop_table('item')
    # ### end Alembic commands ###

