"""create product instance

Revision ID: dc9a935b5428
Revises: 993ec8b86843
Create Date: 2021-12-08 03:46:19.952786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic
revision = 'dc9a935b5428'
down_revision = '993ec8b86843'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('productinstance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('what_do', sa.Text(), server_default='trade', nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('size', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id', 'user_id', 'product_id')
    )
    op.create_index(op.f('ix_productinstance_id'), 'productinstance', ['id'], unique=False)
    op.drop_column('product', 'price')
    op.drop_column('product', 'what_do')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('what_do', sa.TEXT(), server_default=sa.text("'trade'::text"), autoincrement=False, nullable=False))
    op.add_column('product', sa.Column('price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_productinstance_id'), table_name='productinstance')
    op.drop_table('productinstance')
    # ### end Alembic commands ###

